--- 
# file: docker-start.yml
# This file is used for installing a seqware container
   
- hosts: all
  sudo: True
  tasks:
  - name: Start tomcat7 
    service: name=tomcat7 state=started
    ignore_errors: yes
  - name: Start all required services
    service: name={{ item }} state=started 
    with_items: 
     - postgresql
     - hadoop-hdfs-datanode
     - hadoop-hdfs-namenode
     - hadoop-0.20-mapreduce-jobtracker
     - hadoop-0.20-mapreduce-tasktracker
     - oozie
     - gridengine-master
     - gridengine-exec
     
- hosts: all 
  sudo: True
  roles:
    - { role: grid-engine, single_node: True }
