--- 
# file: docker-seqware-install.yml
# This file is used for installing a seqware cluster

# do we need this during the build stage?
- lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 master' owner=root group=root mode=0644
   
   
  # This is a super-fugly way of determining the number of hosts in total, Ansible bug referenced
- hosts: all
  sudo: True
  tasks:
  - name: Determine number of hosts in fugly way 
    include: roles/common/tasks/determine_num_hosts.yml
     
- hosts: all
  sudo: True
  vars:
      shared_storage_system: lvm
      vendor_data: /mnt/seqware-oozie
      lvm_device_whitelist: /dev/xvdd,/dev/xvde
  include: roles/storage/common/tasks/play_deploy_shared_storage.yml
  when: single_node_lvm is defined
     
- hosts: all
  sudo: True
  vars:
      shared_storage_system: glusterfs
      vendor_data: /mnt/seqware-oozie
      glusterfs_version: 3.5 
  include: roles/storage/common/tasks/play_deploy_shared_storage.yml

- hosts: all 
  sudo: True
  roles:
    - { role: docker }

# The grid master depends on the hosts file, as we need to know at least who we
# are by this stage. 
- hosts: master 
  sudo: True
  roles:
    - { role: java, java_provider: Cloudera }
    - { role: grid-engine, grid_engine_master: True }
    - { role: seqware-master-infrastructure }
    - { role: seqware-code }
    - { role: seqware-webservice }

- hosts: worker 
  sudo: True
  roles:
    - { role: java, java_provider: Cloudera }
    - { role: grid-engine, grid_engine_master: False }
    - { role: seqware-worker-infrastructure }
    
- hosts: master 
  sudo: yes
  sudo_user: seqware
  vars: 
      run_integration_tests: false
  roles:
    - { role: seqware-integration-tests, when: "{{ run_integration_tests }} == True" }
    
- hosts: master
  sudo: True
  roles:
    - { role: seqware-cron }
    - { role: seqware-helloworld }
