--- 
# file: docker-start.yml
# This file is used for installing a seqware container
   
- hosts: all
  sudo: True
  tasks:
  - name: Install seqware/seqware_full Docker container
      docker:
        image: seqware/seqware_full

