---
# file: roles/storage/glusterfs/tasks/install.yml
# These tasks are run on all nodes
- name: Storage | Fetch glusterfs signing key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv 774BAC4D

- name: Storage | Add glusterfs repository
  apt_repository: repo='ppa:semiosis/ubuntu-glusterfs-{{ glusterfs_version }}'

- name: Storage | Install latest glusterfs release 
  apt: pkg={{ item.package }} state=present
  with_items:
    - { package: 'xfsprogs' }
    - { package: 'glusterfs-server' }

- include: ../../common/tasks/create_storage_bricks.yml

- include: ../../common/tasks/identify_relevant_bricks.yml

- name: Storage | Create GlusterFS brick volume
  shell: mkdir -p {{ item }}/gv0 creates={{ item }}/gv0
  with_items: bricks.stdout_lines

- name: Storage | Start glusterfs-server
  service: name=glusterfs-server state=started
