---
# file: roles/storage/tasks/glusterfs_start.yml
# These tasks are run only on the master node, and therefore once
- name: Storage | Probe workers
  command: gluster peer probe {{ item }}
  with_items: groups.worker

- name: Storage | Get status
  command: gluster peer status
  register: gluster_status

- name: Storage | Get volume status
  command: gluster volume info
  register: gluster_volume_info
  
- name: Storage | Get volume status actual
  command: gluster volume status
  register: gluster_volume_status

- include: ../../common/tasks/identify_relevant_bricks.yml

- name: Storage | Create volume
  command: gluster volume create gv0 {% for x in groups['master'] %} {% for y in bricks.stdout_lines %}  {{ x }}:{{ y }}/gv0 {% endfor %} {% endfor %} {% for x in groups['worker'] %} {% for y in bricks.stdout_lines %} {{ x }}:{{ y }}/gv0 {% endfor %} {% endfor %} force
  when: gluster_volume_info.stdout.find('gv0') == -1

- name: Storage | Disable built-in NFS to avoid interference with NFS for other directories
  command: gluster volume set gv0 nfs.disable on

- name: Storage | Start volume
  command: gluster volume start gv0
  when: 'not "Status: Started" in gluster_volume_info.stdout_lines'

