---
# file: roles/seqware-helloworld/tasks/artifactory.yml
    
- name:  Download HelloWorld workflow
  get_url: url={{ helloworld_s3_location }} dest=~{{ user_name }}/released-bundles owner=seqware
  
  # this is a repeated piece of code, figure out syntax for sharing tasks
- name: Determine Seqware Version 
  sudo_user: "{{ user_name }}"
  shell: ls ~seqware/.seqware/self-installs/seqware-distribution-*-full.jar | grep -Po "[0-9]+\.[0-9]+\.[0-9]+.*" | sed 's/.\{9\}$//'
  register: det_seqware_version
  changed_when: false
  
- name: Install the workflow
  sudo_user: "{{ user_name }}"
  shell: >
    chdir=~{{ user_name }}/released-bundles creates=~{{ user_name }}/provisioned-bundles/Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_{{ det_seqware_version.stdout }}/Workflow_Bundle_HelloWorld/1.0-SNAPSHOT/metadata.xml
    ~{{ user_name }}/bin/seqware bundle install --zip Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_{{ det_seqware_version.stdout }}.zip