---
# file: roles/seqware-helloworld/tasks/artifactory.yml
    
- name:  Download HelloWorld workflow
  get_url: url={{ helloworld_s3_location }} dest=~{{ user_name }}/released-bundles owner=seqware
  
- include: ../../common/tasks/determine_seqware_version.yml
  
- name: Install the workflow
  sudo_user: "{{ user_name }}"
  shell: >
    chdir=~{{ user_name }}/released-bundles creates=~{{ user_name }}/provisioned-bundles/Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_{{ det_seqware_version.stdout }}/Workflow_Bundle_HelloWorld/1.0-SNAPSHOT/metadata.xml
    ~{{ user_name }}/bin/seqware bundle install --zip Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_{{ det_seqware_version.stdout }}.zip