---
# file: roles/seqware-helloworld/tasks/artifactory.yml
    
- name:  Download HelloWorld workflow
  get_url: url={{ helloworld_s3_location }} dest=~{{ user_name }}/released-bundles owner=seqware
  
- name: Determine Seqware Version 
  sudo_user: "{{ user_name }}"
  shell: chdir=~{{ user_name }}/released-bundles ls Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_*.zip | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?" | head -1
  register: det_seqware_version
  changed_when: false
  
- name: Install the workflow
  sudo_user: "{{ user_name }}"
  shell: >
    chdir=~{{ user_name }}/released-bundles creates=~{{ user_name }}/provisioned-bundles/Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_{{ det_seqware_version.stdout }}/Workflow_Bundle_HelloWorld/1.0-SNAPSHOT/metadata.xml
    ~{{ user_name }}/bin/seqware bundle install --zip Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_{{ det_seqware_version.stdout }}.zip