---
# file: roles/workflow/tasks/install.yml

- name: Detect workflows installed
  command: ls {{ installed_workflows_path }}
  register: provisioned_bundles
  changed_when: false

- name: Download workflows
  sudo_user: "{{ user_name }}"
  get_url: url=http://s3.amazonaws.com/oicr.workflow.bundles/released-bundles/{{ item }}.zip dest={{ target_workflow_path }}/{{ item }}.zip timeout=30
  when: '"{{ item }}" not in provisioned_bundles.stdout'
  register: workflows_downloaded
  with_items: workflows
  retries: 5
  delay: 15

 # note: zip may already have been cleaned up, this is why we're ignoring errors
- name: Setup bundle permissions
  file: path={{ target_workflow_path }}/{{ item }}.zip owner={{ user_name }} group={{ user_name }}
  when:  '"{{ item }}" not in provisioned_bundles.stdout'
  with_items: workflows

- name: Get seqware jar to unzip workflows
  get_url: url=https://seqwaremaven.oicr.on.ca/artifactory/seqware-release/com/github/seqware/seqware-distribution/{{ seqware_version }}/seqware-distribution-{{ seqware_version }}-full.jar dest=/workflows/seqware-distribution-{{ seqware_version }}-full.jar

- name: Unzip workflows
  shell: java -cp /workflows/seqware-distribution-{{ seqware_version }}-full.jar net.sourceforge.seqware.pipeline.tools.UnZip --input-zip {{ target_workflow_path }}/{{ item }}.zip --output-dir {{ target_workflow_path }}/{{ item }}
  args:
    chdir: /workflows
  with_items: workflows

- name: Remove workflow bundles
  command: rm {{ target_workflow_path }}/{{ item }}.zip removes={{ target_workflow_path }}/{{ item }}.zip
  with_items: workflows
