---
# file: roles/java/tasks/oracle8.yml

- name: add repo for java 8
  shell: add-apt-repository -y ppa:webupd8team/java
  become_user: root

- name: set licence selected
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  become_user: root
  changed_when: false

- name: set licence seen
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
  become_user: root
  changed_when: false

- name: install java 8
  apt: name=oracle-java8-installer state=latest update-cache=yes force=yes
  become_user: root

- name: Java | Set JAVA_HOME
  lineinfile:
    line: 'JAVA_HOME=/usr/lib/jvm/java-8-oracle'
    dest: /etc/environment
    state: present
    create: yes
