---
- name: Get Architecture3 jar file
  get_url: url=https://seqwaremaven.oicr.on.ca/artifactory/simple/seqware-release/io/cancer/collaboratory/pancancer-arch-3/{{ pancancer_arch3_version }}/pancancer-arch-3-{{ pancancer_arch3_version }}.jar dest=/home/ubuntu/pancancer-arch-3-{{ pancancer_arch3_version }}.jar

- name: Get kill-worker script
  template: src=kill_worker_daemon.j2 dest=/home/ubuntu/kill_worker_daemon.sh

- name: Get run-worker script
  template: src=run_worker_daemon.j2 dest=/home/ubuntu/run_worker_daemon.sh

- name: queueHost is
  debug: var={{ queueHost }}

- name: Template workerConfig
  template: src=workerConfig.j2 dest=/home/ubuntu/workerConfig.ini owner=ubuntu

- name: Create .seqware directory
  file: path=/home/ubuntu/.seqware state=directory owner=ubuntu
  when: seqware_use_custom_settings is defined and seqware_use_custom_settings

- name: Copy base custom seqware settings
  copy: src=../files/seqware_settings.ini dest=/home/ubuntu/.seqware/settings owner=ubuntu
  when: seqware_use_custom_settings is defined and seqware_use_custom_settings

- name: Uncomment the custom seqware settings, IF you've requested that.
  replace: dest=/home/ubuntu/workerConfig.ini regexp='^(\#seqware-)(.*)$' replace='seqware-\2' backup=yes owner=ubuntu
  when: seqware_use_custom_settings is defined and seqware_use_custom_settings

- name: Run worker as daemon
  sudo: true
  shell: chdir=/home/ubuntu nohup bash /home/ubuntu/run_worker_daemon.sh &
